// File generated by FlutterFire CLI (placeholder — regenerate with
// `flutterfire configure` once a real Firebase project exists).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVZD2-O3tc6ECUhMf_l2URW-AoKoOfXc',
    appId: '1:1045622052946:web:7f6517fa04006b555c278b',
    messagingSenderId: '1045622052946',
    projectId: 'muhasebe-643d9',
    authDomain: 'muhasebe-643d9.firebaseapp.com',
    storageBucket: 'muhasebe-643d9.firebasestorage.app',
    measurementId: 'G-RQY5D94MPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0ZjdjfpZ5lSmBue2GkOPrqgMtYh2MiY',
    appId: '1:1045622052946:android:b92a6281f5e831915c278b',
    messagingSenderId: '1045622052946',
    projectId: 'muhasebe-643d9',
    storageBucket: 'muhasebe-643d9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2AGxSiU4aiv0JR3W3ELtse7p6EBRILCc',
    appId: '1:1045622052946:ios:c4fc4b37d46353665c278b',
    messagingSenderId: '1045622052946',
    projectId: 'muhasebe-643d9',
    storageBucket: 'muhasebe-643d9.firebasestorage.app',
    iosBundleId: 'com.muhasebeci.muhasebeTakip',
  );
}
